name: "Godot Android Export"
on: [push, pull_request]

jobs:
  export-android:
    name: Android Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.2.1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup El Entorno
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/* ~/.local/share/godot/export_templates/

      - name: Crear Directorio de Salida
        run: mkdir -v -p build/android

      - name: Exportar APK con Godot
        run: godot -v --headless --export-release "Android" build/android/NeonCatStation.apk

      - name: Guardar APK Final
        uses: actions/upload-artifact@v4
        with:
          name: Juego-Android-APK
          path: build/android/NeonCatStation.apk
